---
version: '3.3'

services:
  with_ai_gateway:
    image: nginx
    ports: ["8099:80"]
    restart: unless-stopped
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./gateway/well-known:/www/data/.well-known:ro
    depends_on:
      - with_ai_api
      - with_ai_frontend

  with_ai_api:
    build: .
    restart: unless-stopped
    ports: ["8080"]
    volumes:
      - ./with_ai/model:/srv/with_ai/model
      - ./with_ai/model.vectors.npy:/srv/with_ai/model.vectors.npy
    environment:
      - WIA_LOGLEVEL

  with_ai_frontend:
    build: ./tsclient
    restart: unless-stopped
    ports: ["80"]
